set(OCTOCUS_SOURCES	
	main.cpp
        components/SpaceComponents.h
        components/LifeComponents.h
        components/WeaponComponent.h
        components/AiComponents.h
        components/StatusComponents.h
        components/BorderComponent.h
        components/ReplicationId.h
        networking/Serialization.h
        networking/Serialization.cpp
        networking/ByteSwapper.h
        networking/Server.h
        networking/Server.cpp
        networking/GameServer.h
        networking/GameServer.cpp
        networking/GameClient.h
        networking/GameClient.cpp
        networking/Replication.h
        networking/Replication.cpp
        systems/DamageSystem.cpp
        systems/DamageSystem.h
        systems/MovementSystem.h
        systems/MovementSystem.cpp
        systems/AttackSystem.h
        systems/AttackSystem.cpp
        systems/CollisionSystem.h
        systems/CollisionSystem.cpp
        systems/KillSystem.h
        systems/KillSystem.cpp
        systems/AiSystem.h
        systems/AiSystem.cpp
        game.h game.cpp
        WaveSpawner.h WaveSpawner.cpp
)

set(OCTOCUS_CLIENT
        components/RenderComponent.h
        components/Animation.h
        systems/AnimationSystem.h
        systems/AnimationSystem.cpp
        systems/InputSystem.h
        systems/InputSystem.cpp
        systems/DrawSystem.h
        systems/DrawSystem.cpp
)
